version: "3.7"
services:
  postgres:
    image: postgres:12.9
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: descomplica_smasy_pqsl_dev
    volumes:
      - database-data:/var/lib/postgresql/data
    restart: always

  nest-api:
    container_name: nest-api
    image: nest-api
    build: ./students
    ports:
      - 3333:3333
    volumes:
      - ./students:/usr/src/app/students
      - /usr/src/app/students/node_modules
    links:
      - postgres
    depends_on:
      - postgres

  gateway:
    container_name: gateway
    image: gateway
    build: ./gateway
    ports:
      - 8080:8080
    volumes:
      - ./gateway:/usr/src/app/gateway
      - /usr/src/app/gateway/node_modules
    links:
      - nest-api
    depends_on:
      - nest-api

  nextjs-ui:
    build: ./web
    ports:
      - 3000:3000
    container_name: nextjs-ui
    stdin_open: true
    volumes:
      - ./web:/usr/src/app/web
      - /usr/src/app/web/node_modules

volumes:
  database-data:
