version: "3"

services:
  # Application

  database:
    container_name: descomplica_smasy_pqsl_dev
    image: "bitnami/postgresql"
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=descomplica_smasy_pqsl_dev
    volumes:
      - "postgresql_data:/bitnami/postgresql"

volumes:
  postgresql_data:
    driver: local
